CREATE TABLE links(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  slug VARCHAR(8) NOT NULL UNIQUE,
  url TEXT,
  visits BIGINT DEFAULT NULL,
  created TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  last_visited TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

CREATE TABLE visits(
  id BIGSERIAL NOT NULL PRIMARY KEY,
  slug VARCHAR(8) DEFAULT NULL,
  visit_date TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  referer TEXT
);
